name: Mergeability

on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    name: Build & Tests Check
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: amannn/action-semantic-pull-request@v4.5.0
        name: Check PR Semantic Title

      - name: Setuping Node
        uses: actions/setup-node@v3
        with:
          node-version: 15

      - name: NPM Cache
        uses: c-hive/gha-npm-cache@v1.1.0

      - name: Installing Dependencies
        run : npm install

      - name: unit tests
        run: npm run test

      - name: Test Lint
        run: npm run lint
